theme: jekyll-theme-cayman

navigation:
  top:
    links:
      - title: About
        href: /about/
      - title: Link 2
        href: #
      - title: Dropdown
        dropdown:
          - title: SubMenu 1
            href: #
          - title: SubMenu 2
            href: #
          - title: SubMenu 3
            href: #
